// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Days$ReactTemplate = require("./Days.bs.js");
var Cells$ReactTemplate = require("./Cells.bs.js");
var Header$ReactTemplate = require("./Header.bs.js");

function floatStr(str) {
  return String(str | 0);
}

function dayInfo(someDay) {
  var str = someDay.getUTCFullYear();
  var year = String(str | 0);
  var str$1 = someDay.getUTCMonth() + 1.0;
  var month = String(str$1 | 0);
  var str$2 = someDay.getUTCDate();
  var date = String(str$2 | 0);
  var dayStr = year + ("-" + (month + ("-" + date)));
  return /* record */[
          /* year */year,
          /* month */month,
          /* date */date,
          /* str */dayStr
        ];
}

var today = dayInfo(new Date());

var component = ReasonReact.reducerComponent("Calendar");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "bordered responsive-margin"
                        }, ReasonReact.element(undefined, undefined, Header$ReactTemplate.make(today[/* str */3], (function () {
                                    return Curry._1(self[/* send */3], /* Show */0);
                                  }), self[/* state */1][/* show */0], /* array */[])), ReasonReact.element(undefined, undefined, Days$ReactTemplate.make(/* array */[])), ReasonReact.element(undefined, undefined, Cells$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[/* show */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, state) {
              return /* Update */Block.__(0, [/* record */[/* show */!state[/* show */0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.floatStr = floatStr;
exports.dayInfo = dayInfo;
exports.today = today;
exports.component = component;
exports.make = make;
/* today Not a pure module */
