// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Cell");

function cellStyle($staropt$star, _) {
  var b = $staropt$star !== undefined ? $staropt$star : "#bbdefb";
  return {
          background: b,
          margin: "2px",
          padding: "0.5em"
        };
}

function make(day, select, currentMonth, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var match = currentMonth === day[/* month */1];
              var style = match ? cellStyle(undefined, /* () */0) : cellStyle("#e0e0e0", /* () */0);
              return React.createElement("div", {
                          className: "col-sm card cell",
                          style: style,
                          onClick: (function () {
                              return Curry._1(select, day);
                            })
                        }, String(day[/* date */2]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.cellStyle = cellStyle;
exports.make = make;
/* component Not a pure module */
