// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function make(today, handleShow, show, currentMonth, clickPrev, clickNext, clickCurrent, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("p", undefined, "今日: " + today), React.createElement("h2", undefined, String(currentMonth)), React.createElement("button", {
                              onClick: clickPrev
                            }, "上個月"), React.createElement("button", {
                              onClick: clickCurrent
                            }, "這個月"), React.createElement("button", {
                              onClick: clickNext
                            }, "下個月"), React.createElement("button", {
                              onClick: (function () {
                                  console.log("oh");
                                  return /* () */0;
                                })
                            }, "show"), React.createElement("button", {
                              onClick: handleShow
                            }, "show2"), React.createElement("h2", undefined, show ? "hi" : null));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
