// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function yearMonth(year, month) {
  return String(year) + ("-" + String(month));
}

function selectDateTxt(param) {
  var someDay = param[0];
  var dayStr = someDay !== undefined ? someDay[/* str */3] : param[1];
  return "Selected date: " + dayStr;
}

function make(todayStr, currentMonth, currentYear, selectedDate, clickPrev, clickNext, clickCurrent, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("p", undefined, "Today" + todayStr), React.createElement("p", undefined, selectDateTxt(/* tuple */[
                                  selectedDate,
                                  todayStr
                                ])), React.createElement("h2", undefined, yearMonth(currentYear, currentMonth)), React.createElement("button", {
                              onClick: clickPrev
                            }, "< Prev month"), React.createElement("button", {
                              onClick: clickCurrent
                            }, "This month"), React.createElement("button", {
                              onClick: clickNext
                            }, "Next month >"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.yearMonth = yearMonth;
exports.selectDateTxt = selectDateTxt;
exports.make = make;
/* component Not a pure module */
