// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var HelloReact = require("./Hello.react");
var DayUtil$ReactTemplate = require("./DayUtil.bs.js");

function make(selectedDay, todayStr, children) {
  return ReasonReact.wrapJsForReason(HelloReact, {
              selectedDayStr: DayUtil$ReactTemplate.selectDateTxt(/* tuple */[
                    selectedDay,
                    todayStr
                  ])
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
